### PR TITLE
Store the parents of a class in the ClassSymbol instead of the ClassInfo.

### PR DESCRIPTION
**Pull request by sjrd**
Unlike in dotc, we don't have different periods, so we will always have the same parent list for any given class.

### CODE REVIEW

**Comment by bishabosha** [comment]
perhaps we will have an encoding where associated class info changes based on different versions of the classpath?

**Comment by sjrd** [comment]
Perhaps, but we have no idea, and the same "perhaps" can be asked of virtually *everything* we do currently. We will add the necessary indirections in the future if we need them.

**Comment by sjrd** [comment]
In fact, we will almost certainly need different *symbols* for different versions of any given class on different classpaths. Because they would come from different .class/.tasty files, and so would be created in two different instances of the Unpicklers.

**Review by bishabosha — APPROVED** [review]
Looks good overall

**Pull request merged**
